-- ─────────────────────────────────────────────────────────────────────────────
-- Migration: Badge NFT mint state
-- Safe additive migration — uses ADD COLUMN IF NOT EXISTS / CREATE TABLE IF NOT
-- EXISTS / CREATE INDEX IF NOT EXISTS throughout. Safe to re-run.
--
-- Run in the Supabase SQL editor (project: ezqydkrhtpobcwtmfgii) or via
-- supabase db push.
--
-- ── What this migration does ─────────────────────────────────────────────────
--
--   1. Adds onchain mint state columns to user_badges.
--      All existing rows keep minted_onchain = false → they become
--      "Ready to Mint" state.  No data is deleted or modified.
--
--   2. Creates badge_mint_nonces table for EIP-712 nonce replay prevention.
--      The nonce is generated by the backend mint-signature API (Phase 5)
--      and consumed by the PATCH /api/badges endpoint after the user's
--      mintBadge() transaction confirms.
--
-- ── Badge state model after this migration ───────────────────────────────────
--
--   Locked         → no user_badges row for this badge
--   Ready to Mint  → user_badges row exists, minted_onchain = false
--   Owned on Base  → user_badges row exists, minted_onchain = true
--
-- ── XP note ──────────────────────────────────────────────────────────────────
--
--   XP is awarded when a badge is earned (user_badges row inserted by the
--   award engine). Minting the NFT grants NO additional XP. This migration
--   does not touch xp_events, profiles.xp, or leaderboard_stats.
--
-- ── PrediXIBadges contract reference ─────────────────────────────────────────
--
--   Contract: 0x87231AA7FAeB23B3E674E905d7af4B1c91E10B2d (Base Mainnet, chain 8453)
--   Token IDs 1–19 → current badges (see src/lib/badges/tokenIds.ts, Phase 4)
--   Token IDs 20–25 → reserved
--
-- ─────────────────────────────────────────────────────────────────────────────


-- =============================================================================
-- 1. user_badges — add onchain mint state columns
-- =============================================================================

ALTER TABLE user_badges
  -- Whether this badge has been minted as an NFT on Base.
  -- false = Ready to Mint (earned but not yet minted).
  -- true  = Owned on Base (mint tx confirmed and persisted).
  ADD COLUMN IF NOT EXISTS minted_onchain  boolean     NOT NULL DEFAULT false,

  -- Timestamp when the mint was persisted (set by PATCH /api/badges in Phase 5).
  -- NULL until minted_onchain flips to true.
  ADD COLUMN IF NOT EXISTS minted_at       timestamptz NULL,

  -- Base Mainnet transaction hash of the mintBadge() call.
  -- NULL until minted_onchain flips to true.
  ADD COLUMN IF NOT EXISTS onchain_tx_hash text        NULL,

  -- ERC-1155 token ID on the PrediXIBadges contract (1–25).
  -- NULL until minted_onchain flips to true.
  -- See Phase 4 token ID mapping: src/lib/badges/tokenIds.ts
  ADD COLUMN IF NOT EXISTS token_id        integer     NULL,

  -- Chain ID of the minting network. Always 8453 (Base Mainnet) for new rows.
  ADD COLUMN IF NOT EXISTS chain_id        integer     NOT NULL DEFAULT 8453;

-- ── Token ID constraint ───────────────────────────────────────────────────────
-- Prevents storing out-of-range token IDs (mirrors MIN/MAX_TOKEN_ID in the
-- PrediXIBadges contract). NULL is allowed until the badge is minted.
-- The constraint name uses IF NOT EXISTS syntax via a DO block for idempotency.

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE table_name = 'user_badges'
      AND constraint_name = 'chk_user_badges_token_id_range'
  ) THEN
    ALTER TABLE user_badges
      ADD CONSTRAINT chk_user_badges_token_id_range
      CHECK (token_id IS NULL OR (token_id >= 1 AND token_id <= 25));
  END IF;
END
$$;

-- ── Mint consistency constraint ───────────────────────────────────────────────
-- When minted_onchain = true, the supporting columns must all be non-null.
-- Prevents partial mint state (e.g. minted_onchain=true but no tx hash stored).
-- Soft constraint — only fires on INSERT/UPDATE, not on existing rows.

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE table_name = 'user_badges'
      AND constraint_name = 'chk_user_badges_mint_consistency'
  ) THEN
    ALTER TABLE user_badges
      ADD CONSTRAINT chk_user_badges_mint_consistency
      CHECK (
        minted_onchain = false
        OR (
          minted_onchain = true
          AND minted_at       IS NOT NULL
          AND onchain_tx_hash IS NOT NULL
          AND token_id        IS NOT NULL
        )
      );
  END IF;
END
$$;

-- ── Indexes ───────────────────────────────────────────────────────────────────

-- Fast lookup: "which wallets have minted badge X as an NFT?"
-- Partial index — only indexes the small fraction of rows where minted_onchain=true.
CREATE INDEX IF NOT EXISTS idx_user_badges_minted_onchain
  ON user_badges (profile_id, badge_id)
  WHERE minted_onchain = true;

-- Fast lookup: "get all minted badges for a wallet" (profile page, Phase 7).
CREATE INDEX IF NOT EXISTS idx_user_badges_token_id
  ON user_badges (token_id)
  WHERE token_id IS NOT NULL;


-- =============================================================================
-- 2. badge_mint_nonces — EIP-712 nonce replay prevention
-- =============================================================================
--
-- Each row represents one backend-issued mint authorisation.
-- The nonce is generated by GET /api/badges/mint-signature (Phase 5) and stored
-- here so the PATCH /api/badges endpoint can verify it was legitimately issued.
--
-- Lifecycle:
--   1. User requests mint signature → backend inserts row with used_at = NULL.
--   2. User sends mintBadge() tx on Base → tx confirms.
--   3. User calls PATCH /api/badges → backend sets used_at = now().
--
-- The PrediXIBadges contract also tracks usedNonces on-chain; this table is the
-- off-chain mirror used by the backend to detect replays before hitting the RPC.

CREATE TABLE IF NOT EXISTS badge_mint_nonces (
  -- The bytes32 nonce value as a hex string (0x-prefixed, 66 chars).
  -- Matches the nonce field in the EIP-712 MintBadge struct.
  nonce           text        PRIMARY KEY,

  -- Lowercase 0x wallet address that was issued this nonce.
  wallet_address  text        NOT NULL,

  -- badge_id from user_badges / src/data/badges.ts (e.g. 'first-pred').
  badge_id        text        NOT NULL,

  -- ERC-1155 token ID on the PrediXIBadges contract (1–25).
  token_id        integer     NOT NULL
                              CONSTRAINT chk_nonce_token_id_range
                              CHECK (token_id >= 1 AND token_id <= 25),

  -- When this nonce was generated and issued to the user.
  created_at      timestamptz NOT NULL DEFAULT now(),

  -- When this nonce was consumed (mint tx confirmed and persisted).
  -- NULL = nonce was issued but not yet used.
  -- NOT NULL = nonce is spent; reject any replay attempt.
  used_at         timestamptz NULL
);

COMMENT ON TABLE badge_mint_nonces IS
  'EIP-712 nonce tracking for PrediXIBadges mint authorisations. '
  'One row per issued signature. used_at is set after mint tx confirms.';

COMMENT ON COLUMN badge_mint_nonces.used_at IS
  'NULL = nonce is live (not yet used). Set to now() after PATCH /api/badges '
  'confirms the mint transaction on Base.';

-- ── Indexes ───────────────────────────────────────────────────────────────────

-- Phase 5: "has this wallet already been issued an unused nonce for this badge?"
-- Prevents double-issuing signatures before the first mint confirms.
CREATE INDEX IF NOT EXISTS idx_badge_mint_nonces_wallet_badge
  ON badge_mint_nonces (wallet_address, badge_id);

-- Phase 5: look up nonces by wallet (list pending mints).
CREATE INDEX IF NOT EXISTS idx_badge_mint_nonces_wallet
  ON badge_mint_nonces (wallet_address);

-- Phase 5: look up by token_id (contract-side view).
CREATE INDEX IF NOT EXISTS idx_badge_mint_nonces_token_id
  ON badge_mint_nonces (token_id);

-- Partial index on unused nonces — the hot path for replay checks.
-- Most nonces will eventually have used_at set; this index stays small.
CREATE INDEX IF NOT EXISTS idx_badge_mint_nonces_unused
  ON badge_mint_nonces (wallet_address, badge_id)
  WHERE used_at IS NULL;
