/**
 * Base Launch Metadata Config
 *
 * Single source of truth for all app identity, store listing, and submission
 * metadata used during Base App / Mini App registration.
 *
 * All URLs are placeholders — replace with real values before submission.
 * No secrets. No tokens. Safe to commit.
 */

export const BASE_LAUNCH_CONFIG = {
  // ── Identity ───────────────────────────────────────────────────────────────

  appName:          'PrediXI',
  tagline:          'Predict. Earn. Compete On-Chain.',
  shortDescription: 'Web3 football prediction platform built for Base App. Predict match outcomes, earn XP, and climb the leaderboard — all on Base.',

  longDescription: `PrediXI is a Web3 football prediction platform built natively for Base App and Coinbase Smart Wallet. \
Predict the outcomes of top football matches, earn XP for every correct call, and compete against other predictors on a live on-chain leaderboard. \
Every prediction is cryptographically signed by your wallet and committed to a tamper-evident hash — giving you provable, auditable prediction history. \
Built on Base for fast, low-cost transactions and seamless Coinbase Smart Wallet / Base Account integration.`,

  // ── Store Listing ──────────────────────────────────────────────────────────

  categories:        ['sports', 'gaming', 'defi'] as const,
  primaryCategory:   'sports' as const,
  tags:              ['football', 'prediction', 'xp', 'leaderboard', 'base', 'wallet', 'web3'],

  // ── URLs ──────────────────────────────────────────────────────────────────

  appUrl:         'https://predixi-base.vercel.app',
  supportUrl:     'https://predixi-base.vercel.app/support',
  privacyUrl:     'https://predixi-base.vercel.app/privacy',
  termsUrl:       'https://predixi-base.vercel.app/terms',
  iconUrl:        'https://predixi-base.vercel.app/icon',
  ogImageUrl:     'https://predixi-base.vercel.app/opengraph-image',   // generated by src/app/opengraph-image.tsx

  // ── Contact ────────────────────────────────────────────────────────────────

  supportEmail:   'support@predixi.app',   // placeholder — set up before submission

  // ── Social ────────────────────────────────────────────────────────────────

  socialLinks: {
    twitter:  'https://x.com/predixi_app',      // placeholder
    farcaster: 'https://warpcast.com/predixi',  // placeholder
    github:   'https://github.com/predixi',     // placeholder
  },

  // ── Chain + Wallet ────────────────────────────────────────────────────────

  supportedChains:    ['base'] as const,
  requiredWallets:    ['coinbase_smart_wallet', 'base_account'] as const,
  walletFeatures:     ['sign_message', 'erc6492', 'erc1271'] as const,

  // ── Assets (paths relative to /public) ────────────────────────────────────

  assets: {
    /** App icon — must be square PNG, minimum 192×192, ideally 512×512 */
    appIcon:          '/brand/predixi-logo.png',

    /** OG/share image — 1200×630 PNG — NEEDS CREATING before submission */
    ogImage:          '/brand/og-image.png',

    /** Favicon — NEEDS CREATING: /public/favicon.ico (32×32) */
    favicon:          '/favicon.ico',

    /** Apple touch icon — NEEDS CREATING: /public/apple-touch-icon.png (180×180) */
    appleTouchIcon:   '/apple-touch-icon.png',
  },

  // ── Base App Registration Fields ──────────────────────────────────────────

  baseAppId:       '69fc81c8bced645c370bd8fe',   // from existing base:app_id meta tag
  minBaseVersion:  '1.0.0',

  // ── Review Notes ──────────────────────────────────────────────────────────

  reviewNotes: `PrediXI is a sports prediction game — not financial advice and not a gambling product. \
Users predict football match outcomes for XP points and leaderboard ranking only. \
No real-money wagering. No token trading. No financial transactions. \
Wallet signatures are used for identity and prediction authenticity, not payments.`,

} as const

export type BaseLaunchConfig = typeof BASE_LAUNCH_CONFIG
