/**
 * Onchain Commitment Hashing
 *
 *   commitmentHash = keccak256(deterministicJSON(payload))
 *
 * All three submission types compute the hash client-side BEFORE calling
 * submitCommitment() on Base. The server re-derives the same hash from the
 * request body and verifies it against the on-chain CommitmentSubmitted event.
 *
 * Commitment types:
 *   prediction    — wallet + matchId + outcome + clientTimestamp + clientNonce
 *   daily-xi      — wallet + entryDate + playerIds (sorted) + projectedMaxXp
 *   wc-prediction — wallet + predictionKey + selectedValue + xpReward
 */

import { keccak256, toBytes } from 'viem'

// ── Deterministic JSON serialisation ─────────────────────────────────────────
// Recursively sorts object keys so insertion order never affects the output.

function deterministicStringify(value: unknown): string {
  if (value === null || value === undefined) return JSON.stringify(value)
  if (Array.isArray(value)) {
    return '[' + value.map(deterministicStringify).join(',') + ']'
  }
  if (typeof value === 'object') {
    const obj  = value as Record<string, unknown>
    const keys = Object.keys(obj).sort()
    const parts = keys.map(k => JSON.stringify(k) + ':' + deterministicStringify(obj[k]))
    return '{' + parts.join(',') + '}'
  }
  return JSON.stringify(value)
}

// ── Core hash function ────────────────────────────────────────────────────────

export function hashCommitment(payload: Record<string, unknown>): string {
  const canonical = deterministicStringify(payload)
  return keccak256(toBytes(canonical))
}

// ── Commitment result type ────────────────────────────────────────────────────

export type CommitmentResult = {
  payload:         Record<string, unknown>
  commitmentHash:  string
}

// ── Per-type commitment builders ──────────────────────────────────────────────

/**
 * Match prediction commitment.
 *
 * Transaction-first: both clientNonce and clientTimestamp are generated by the
 * client BEFORE calling submitCommitment() on Base. The server re-derives this
 * hash from the same values in the POST body to verify the on-chain event.
 *
 * clientNonce  — crypto.randomUUID() generated client-side; collision-resistant
 *                uniqueness per prediction without depending on a DB-assigned UUID.
 * clientTimestamp — ISO timestamp from the client; used in the hash payload for
 *                   human-readable traceability, not for freshness enforcement.
 */
export function createPredictionCommitment(input: {
  walletAddress:   string
  matchId:         string
  outcome:         string
  clientTimestamp: string  // ISO timestamp generated client-side before TX
  clientNonce:     string  // crypto.randomUUID() generated client-side before TX
}): CommitmentResult {
  const payload: Record<string, unknown> = {
    type:            'prediction',
    walletAddress:   input.walletAddress.toLowerCase(),
    matchId:         input.matchId,
    outcome:         input.outcome,
    clientTimestamp: input.clientTimestamp,
    clientNonce:     input.clientNonce,
  }
  return { payload, commitmentHash: hashCommitment(payload) }
}

/** Daily XI commitment — playerIds sorted for determinism */
export function createDailyXICommitment(input: {
  walletAddress:  string
  entryDate:      string
  playerIds:      string[]
  projectedMaxXp: number
}): CommitmentResult {
  const payload = {
    type:           'daily-xi',
    walletAddress:  input.walletAddress.toLowerCase(),
    entryDate:      input.entryDate,
    playerIds:      [...input.playerIds].sort(),
    projectedMaxXp: input.projectedMaxXp,
  }
  return { payload, commitmentHash: hashCommitment(payload) }
}

/** World Cup prediction commitment */
export function createWCCommitment(input: {
  walletAddress:  string
  predictionKey:  string
  selectedValue:  string[]
  xpReward:       number
}): CommitmentResult {
  const payload = {
    type:          'wc-prediction',
    walletAddress: input.walletAddress.toLowerCase(),
    predictionKey: input.predictionKey,
    selectedValue: input.selectedValue,
    xpReward:      input.xpReward,
  }
  return { payload, commitmentHash: hashCommitment(payload) }
}
